version: "3"
services:
  sonarqube:
    image: sonarqube:community
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: admin
      SONAR_JDBC_PASSWORD: admin
    volumes:
      - ./.volumes/sonarqube/data:/.volumes/sonarqube/data
      - ./.volumes/sonarqube/extensions:/.volumes/sonarqube/extensions
      - ./.volumes/sonarqube/logs:/.volumes/sonarqube/logs
    ports:
      - "9000:9000"
  db:
    image: postgres:13
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sonar
    volumes:
      - ./.volumes/postgres:/var/lib/postgresql
      - ./.volumes/postgres/data:/var/lib/postgresql/data